version: "3.8"

services:
  redis:
    image: redis:6.0.9-alpine
    container_name: api_redis
    ports:
     - "6379:6379"
    restart: always
    networks:
     - web_api

  postgresql:
    image: postgres:12-alpine
    container_name: api_postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=currency_db
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - web_api

  prometheus:
    container_name: prometheus_container
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus:/etc/monitoring
      - prometheus-data:/monitoring
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml  # If you use --web.enable-lifecycle you can reload configuration files (e.g. rules) without restarting Prometheus:
    networks:
      - web_api

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources # data source configuration
      - grafana-data:/var/lib/grafana # used to save dashboards
    networks:
      - web_api

  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - "./monitoring:/config"
      - alertmanager-data:/data
    networks:
      - web_api

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - web_api

  jaeger:
    container_name: jaeger_container
    restart: always
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - web_api

volumes:
  db:
  prometheus-data:
  grafana-data:
  alertmanager-data:

networks:
  web_api:
    driver: bridge